<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.2.1
# *Querying the International Space Station*

## The OpenNotify API

The OpenNotify API exposes a few attributes of the International Space Station (ISS) via a simple, authentication-free interface. The simplicity of this API precludes any need for a dedicated Python library. However, as with many APIs, it accepts requests according to HTTP standards and returns responses in JSON format, so the Python libraries request and json will make managing the I/O simpler still.

In [3]:
import requests
import json
from datetime import datetime, date, time

This request fetches the latest position of the international space station:

In [5]:
response = requests.get("http://api.open-notify.org/iss-now.json")

Print the status code and text of the response:

In [6]:
#ANSWER
print(response.status_code)

200


In [13]:
#ANSWER
print(response.text)

{"api_status":"ALPHA","request_timestamp":"2024-01-25T07:17:09.129951769Z","norad_id":25544,"satellite_name":"ISS","tle_last_retrieved":"2024-01-24T23:39:26.520532517Z","lat":-33.87,"lon":151.21,"hours":24,"min_elevation":0,"query_ms":19,"passes":[{"start":"2024-01-25T14:29:39.111Z","tca":"2024-01-25T14:33:09.111Z","end":"2024-01-25T14:36:54.111Z","aos_azimuth":15,"los_azimuth":99,"max_elevation":6.0},{"start":"2024-01-25T16:03:59.111Z","tca":"2024-01-25T16:09:29.111Z","end":"2024-01-25T16:14:59.111Z","aos_azimuth":315,"los_azimuth":132,"max_elevation":83.0},{"start":"2024-01-25T17:41:54.111Z","tca":"2024-01-25T17:46:24.111Z","end":"2024-01-25T17:51:19.111Z","aos_azimuth":265,"los_azimuth":148,"max_elevation":12.0},{"start":"2024-01-25T19:21:44.111Z","tca":"2024-01-25T19:24:44.111Z","end":"2024-01-25T19:27:49.111Z","aos_azimuth":220,"los_azimuth":153,"max_elevation":3.0},{"start":"2024-01-25T20:59:49.111Z","tca":"2024-01-25T21:03:19.111Z","end":"2024-01-25T21:06:49.111Z","aos_azimuth":

We can use another API to request the current position of the ISS and the next few times at which it will be over a certain location. The latitude and longitude of Sydney are (-33.87, 151.21).

In [9]:
response = requests.get("https://api.g7vrd.co.uk/v1/satellite-passes/25544/-33.87/151.21.json?minelevation=0&hours=24")

Print the response header:

In [ ]:
#ANSWER


Print the content of the response (the data that the server returned):

In [ ]:
#ANSWER


Note that this is a Python byte string:

In [ ]:
print(type(response.content))

Print just the "content-type" value from the header:

In [ ]:
#ANSWER


JSON was designed to be easy for computers to read, not for people. The `requests` library can decode the JSON byte string:

In [ ]:
overheads = response.json()
print(overheads)

What kind of object did this give us?

In [ ]:
#ANSWER:


Python dicts are easier to work with, but the data we want is still buried in that data structure, so we have to dig it out. First, extract the `passes` value to a separate list:

In [ ]:
#ANSWER:


Now extract the `start` strings into an array called `srisetimes`:

In [ ]:
#ANSWER:


These are strings. We convert these to an array of Python `datetime` values called `risetimes`:

In [ ]:
risetimes = [datetime.strptime(xpass['start'], "%Y-%m-%dT%H:%M:%S.%fZ") for xpass in passes]
risetimes

Finally, use `risetime.strftime` to print these in a format that people understand:

```
e.g.
18/10/22 07:05
18/10/22 08:41
18/10/22 10:20
18/10/22 12:00
18/10/22 01:37
18/10/22 03:13
```



In [ ]:
#ANSWER:


Finally, here is an endpoint that tells us who is on board:

In [ ]:
response = requests.get("http://api.open-notify.org/astros.json")

Referring to the methods used above, extract the number of astronauts and their names:

In [ ]:
#ANSWER:


## HOMEWORK


1. Write a simple handler for the response status code (refer to lab resources slide for HTTP response codes). As this Jupyter Notebook is an interactive device, the handler does not need to manage subsequent code execution (i.e. by branching or aborting execution), although it should return something that could be used to do so if deployed in a Python program.

In [ ]:
#ANSWER:
def handleResponse(response, verbose = False):
    '''
    Returns Boolean Value, Status Code,
    '''
  # if Status Code is 200 return false, and status code
  # Otherwise Return True and Status Code

2. Test your response handler on some correct and incorrect API calls.

In [ ]:
response = requests.get("http://api.open-notify.org/astros.json")
if handleResponse(response)[0]:
    print('API call failed. Resolve issue before continuing!')

response = requests.get("http://api.open-notify.org/iss-now.json")
handleResponse(response, True)[0]

>

>

>



---



---



> > > > > > > > > © 2022 Institute of Data


---



---



